### ISSUE TITLE
Active Link

### ISSUE THREAD

**Issue by dezrtroze** [Labs64/credit-tracker#19]
Hi there, i love this plugin very much. It's made life so much easier. Many thanks!
I wanted to ask if there is any way to make the link category in the credits table active ?
Since I have gotten permission from many sources to add their content on my site, they have required active links to their pages.

**Comment by r-brown** [comment]
Hi @dezrtroze,

Thank you for using Credit Tracker.
We'll try to address this issue in one of the next pluging releases.

Best Regards,
  Ready

**Comment by r-brown** [comment]
Fixed by https://github.com/Labs64/credit-tracker/commit/a13484acbb83d8d6aab05ed64bde7a834e14a588

_include_columns_ attribute of _credit_tracker_table_ extended by: _link, source, title, caption_

You can generate table with the specified columns only and defined columns order:
`[credit_tracker_table include_columns="ident_nr,copyright,license,author,publisher,link,source,title,caption"]`
