### ISSUE TITLE
Credit Tracker Information Not showing Up

### ISSUE THREAD

**Issue by sfrederi7** [Labs64/credit-tracker#25]
I Installed Credit Tracker on my site. The information (author/link) is not showing up under the photo. Not sure what is interfering or keeping the information from displaying.
![credit tracker issue](https://user-images.githubusercontent.com/20713883/28749408-6b75f65e-7494-11e7-9f84-1a9e3343a983.png)

**Comment by sfrederi7** [comment]
My site is blog.curlscout.com

**Comment by r-brown** [comment]
Hi @sfrederi7,

I've verified latest version of [Credit Tracker](https://wordpress.org/plugins/credit-tracker/) with Wordpress 4.8

Using screen flow below you will be able to setup Credit Tracker on your blog.

## Make sure you've provided additionalö media attribution (e.g. Ident-Nr., Author, etc.)
<img width="1602" alt="issue-25-01" src="https://user-images.githubusercontent.com/1361258/28763601-8fcc81a4-75bf-11e7-8a43-e5108f760a1b.png">

## In Credit Tracker Settings define your _Copyright format_ pattern and enable _Override shortcodes_
<img width="1608" alt="issue-25-02" src="https://user-images.githubusercontent.com/1361258/28763604-8fd9d124-75bf-11e7-8461-36667816d4f5.png">

## Paste media in a blog post and click on edit
<img width="1149" alt="issue-25-03" src="https://user-images.githubusercontent.com/1361258/28763603-8fd9690a-75bf-11e7-9b29-a59d8c6371d7.png">

## Define some dummy _Caption_ in order to get Wordpress caption shortcode
<img width="1382" alt="issue-25-04" src="https://user-images.githubusercontent.com/1361258/28763605-8fdb7fba-75bf-11e7-83c0-a98892650135.png">

## ... or add this manually in Text mode (please make sure you are using correct _id_ for your media)
<img width="1146" alt="issue-25-05" src="https://user-images.githubusercontent.com/1361258/28763602-8fd1f828-75bf-11e7-8f04-6b741daf619f.png">

## Post preview will show you new rendered caption
<img width="1083" alt="issue-25-06" src="https://user-images.githubusercontent.com/1361258/28763606-8fe2d03a-75bf-11e7-9e75-fcec97c04973.png">

Please let me know, whether this is helping you.

Best,
  R.Brown
