### ISSUE TITLE
Add credit to the thumbnail

### ISSUE THREAD

**Issue by r-brown** [Labs64/credit-tracker#9]
Add the credit to the image from thumbnail (the featured image) that reappears at the top of the actual post.

**Comment by r-brown** [comment]
Hi, we'd like to automatically show the image credit on (or just below) the post's featured image, just as here: http://prntscr.com/a759en or here: http://prntscr.com/a6ma3l how can we accomplish that?

source: https://wordpress.org/support/topic/image-credit-on-featured-image

**Comment by Jaace** [comment]
I can look into this.

**Comment by Jaace** [comment]
A few questions: should the credit be just the Author/Owner field on the image or a combination of the fields, like: author/owner, source, publisher?

From the screenshot it looks like maybe just the author and the publisher?

Additionally, does this feature need to have an option to choose above/below the photo for this information? If we go down that path, we'd probably need to add a color setting so that if it's over the photo the text is visible, if it's light or dark.

**Comment by Jaace** [comment]
PR opened here: https://github.com/Labs64/credit-tracker/pull/27

Let me know about the question above and I can modify to pull in the other data, if needed.

**Comment by Jaace** [comment]
Absolutely, I can look into that this weekend!

**Comment by Jaace** [comment]
@r-brown I've pushed up changes to address the use of the copyright format field.  The PR has been updated here: https://github.com/Labs64/credit-tracker/pull/27

Thanks!

**Comment by r-brown** [comment]
Additional fine-tunings:

- move logic to the `credit-tracker-shortcodes.php`
- add the switch to allow enable disable thumbnail credit rendering (default: true)
- fix error due to the missing thumbnail image
